// Module included in the following assemblies:
//
// * storage/dynamic-provisioning.adoc
// * post_installation_configuration/storage-configuration.adoc

[id="azure-disk-definition_{context}"]
= Azure Disk object definition

.azure-advanced-disk-storageclass.yaml
[source,yaml]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/azure-disk
volumeBindingMode: WaitForFirstConsumer <1>
allowVolumeExpansion: true
parameters:
  kind: Managed <2>
  storageaccounttype: Premium_LRS <3>
reclaimPolicy: Delete
----
<1> Using `WaitForFirstConsumer` is strongly recommended. This provisions the volume while allowing enough storage to schedule the pod on a free worker node from an available zone.
<2> Possible values are `Shared` (default), `Managed`, and `Dedicated`.
<3> Azure storage account SKU tier. Default is empty. Note that Premium VMs can attach both `Standard_LRS` and `Premium_LRS` disks, Standard VMs can only attach `Standard_LRS` disks, Managed VMs can only attach managed disks, and unmanaged VMs can only attach unmanaged disks.
+
.. If `kind` is set to `Shared`, Azure creates all unmanaged disks in a few shared storage accounts in the same resource group as the cluster.
.. If `kind` is set to `Managed`, Azure creates new managed disks.
.. If `kind` is set to `Dedicated` and a `storageAccount` is specified, Azure uses the specified storage account for the new unmanaged disk in the same resource group as the cluster. For this to work:
 * The specified storage account must be in the same region.
 * Azure Cloud Provider must have write access to the storage account.
.. If `kind` is set to `Dedicated` and a `storageAccount` is not specified, Azure creates a new dedicated storage account for the new unmanaged disk in the same resource group as the cluster.
+
[IMPORTANT]
====
Red Hat does not support the use of `kind: Dedicated` in the storage class. {product-title} creates a managed disk for machine OS, or root, disks. However, Azure Disk does not allow the use of both managed and unmanaged disks on a node. Therefore, unmanaged disks cannot be attached to {product-title} nodes.
====
