// Module included in the following assemblies:
//
// * storage/container_storage_interface/persistent-storage-csi-ebs.adoc

[id="persistent-storage-csi-ebs-operator-install_{context}"]
= Installing the AWS Elastic Block Store CSI Operator

The AWS Elastic Block Store (EBS) Container Storage Interface (CSI) Operator enables the replacement of the existing AWS EBS in-tree storage plug-in.

When you install the AWS EBS CSI Operator, {product-title} provides the CSI driver that allows you to use CSI volumes with the `PersistentVolumeClaims`, `PersistentVolumes`, and `StorageClasses` API objects.

The AWS EBS CSI Operator is not installed in {product-title} by default. Use the following procedure to install and configure this Operator to enable the AWS EBS CSI driver in your cluster.

.Prerequisites
* Access to the `oc` command-line interface (CLI) or the {product-title} web console.

.Procedure
Install the AWS EBS CSI Operator from the web console by completing the following steps.

. Log in to the web console.

. Navigate to *Operators* -> *OperatorHub*.

. Type *AWS EBS CSI* into the filter box to locate the AWS EBS CSI Operator.

. Click *Install*.

. On the *Create Operator Subscription* page, select *A specific namespace on the cluster*. Select *openshift-aws-ebs-csi-driver-operator* from the drop-down menu.

. Adjust the values for the *Update Channel* and *Approval Strategy* to the desired values.

. Click *Install*.

Once finished, the AWS EBS CSI Operator will be listed in the *Installed Operators* section of the web console.
